// <auto-generated />
using System;
using Koeman_INTDEV_SE_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Koeman_INTDEV_SE_1.Migrations
{
    [DbContext(typeof(DbContextINTDEV1))]
    [Migration("20250521083452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Koeman_INTDEV_SE_1.Models.Bestelling", b =>
                {
                    b.Property<int>("BestellingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Besteldatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("KlantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Totaalbedrag")
                        .HasColumnType("TEXT");

                    b.HasKey("BestellingId");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestellingen");
                });

            modelBuilder.Entity("Koeman_INTDEV_SE_1.Models.BestellingProduct", b =>
                {
                    b.Property<int>("BestellingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aantal")
                        .HasColumnType("INTEGER");

                    b.HasKey("BestellingId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BestellingProducten");
                });

            modelBuilder.Entity("Koeman_INTDEV_SE_1.Models.Klant", b =>
                {
                    b.Property<int>("KlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KlantId");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("Koeman_INTDEV_SE_1.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Producten");
                });

            modelBuilder.Entity("Koeman_INTDEV_SE_1.Models.Bestelling", b =>
                {
                    b.HasOne("Koeman_INTDEV_SE_1.Models.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("Koeman_INTDEV_SE_1.Models.BestellingProduct", b =>
                {
                    b.HasOne("Koeman_INTDEV_SE_1.Models.Bestelling", "Bestelling")
                        .WithMany("BestellingProducten")
                        .HasForeignKey("BestellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koeman_INTDEV_SE_1.Models.Product", "Product")
                        .WithMany("BestellingProducten")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestelling");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Koeman_INTDEV_SE_1.Models.Bestelling", b =>
                {
                    b.Navigation("BestellingProducten");
                });

            modelBuilder.Entity("Koeman_INTDEV_SE_1.Models.Klant", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("Koeman_INTDEV_SE_1.Models.Product", b =>
                {
                    b.Navigation("BestellingProducten");
                });
#pragma warning restore 612, 618
        }
    }
}
